name: 'Rum Dogs, Inc.'
favicon: null
layout_spectrum: 0.32843309780582786
typography_spectrum: 0.619499898981303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.06116100889630616
  lightness: 0.6987327185925096
  saturation: 0.9189004383515567
  rhythmicContrast: 0.2460476546548307
purpose: []
